name: Check Base Branch

# События, при которых workflow запускается
on:
  pull_request:
    types: [opened, synchronize, reopened, edited] # Запускается при открытии, синхронизации, повторном открытии и редактировании PR

jobs:
  check_base_branch:
    runs-on: ubuntu-latest # Запускается на Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Клонирует репозиторий

      - name: Check base branch
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }} # Имя ветки, из которой сделан PR
          GITHUB_BASE_REF: ${{ github.base_ref }} # Базовая ветка PR (куда мержим)
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }} # Владелец репозитория
        run: |
          #!/usr/bin/env bash

          # Проверяем базовую ветку для feature веток
          if [[ "$GITHUB_HEAD_REF" == "add-common-films" ]] || [[ "$GITHUB_HEAD_REF" == "add-director" ]] || [[ "$GITHUB_HEAD_REF" == "add-feed" ]] || [[ "$GITHUB_HEAD_REF" == "add-marks" ]]  || [[ "$GITHUB_HEAD_REF" == "add-most-populars" ]]  || [[ "$GITHUB_HEAD_REF" == "add-recommendations" ]]  || [[ "$GITHUB_HEAD_REF" == "add-remove-endpoint" ]]  || [[ "$GITHUB_HEAD_REF" == "add-reviews" ]] || [[ "$GITHUB_HEAD_REF" == "add-search" ]]; then
              if [[ "$GITHUB_BASE_REF" != "develop" ]] && [[ "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]; then
                  echo "::error title=Wrong Base Branch::Set the pull request to merge branch 'develop' (instead of '$GITHUB_BASE_REF')" # Выводим ошибку в GitHub UI
                  exit 1 # Прерываем workflow
              fi
          # Проверяем базовую ветку для остальных веток
          else
              if [[ "$GITHUB_BASE_REF" != "main" ]] && [[ "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]; then
                  echo "::error title=Wrong Base Branch::Set the pull request to merge branch 'main' (instead of '$GITHUB_BASE_REF')" # Выводим ошибку в GitHub UI
                  exit 1 # Прерываем workflow
              fi
          fi

          echo "Github target '$GITHUB_BASE_REF' - OK" # Выводим сообщение об успехе
